config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
  get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_for :users
  root to: 'cards#index' # Page d'accueil avec toutes les cartes

  resources :cards, only: [:index, :show] do
    member do
      post :add_to_collection
      delete :remove_from_collection
    end
  end

  resources :users, only: [] do
    get :collection, on: :member # Page de collection d'un utilisateur
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :cards_users, dependent: :destroy
  has_many :users, through: :cards_users
  has_and_belongs_to_many :users

  def image_url
    "/assets/#{image_path}" 
  end

  validates :name, :description, :pv, :category, presence: true
end

app/models/cards_user.rb
class CardsUser < ApplicationRecord
  belongs_to :user
  belongs_to :card

  validates :user_id, uniqueness: { scope: :card_id, message: "This card is already in the user's collection." }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cards_users, dependent: :destroy
  has_many :cards, through: :cards_users
  has_and_belongs_to_many :cards
  # Devise modules (ajoutez si nécessaire)
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @cards = Card.all.distinct
  end

  def show
    @card = Card.find(params[:id])
    @in_collection = current_user.cards.exists?(@card.id)
  end

  def add_to_collection
    card = Card.find(params[:id])

    # Si le Pokémon n'est pas déjà dans la collection de l'utilisateur, on l'ajoute
    unless current_user.cards.exists?(card.id)
      current_user.cards << card
      flash[:notice] = 'Ce Reloumon a été attrapé et ajouté à votre collection !'  # Message de succès
    else
      flash[:alert] = 'Ce Reloumon est déjà dans votre collection.'  # Message d'alerte si déjà dans la collection
    end

    # Redirection vers la page de la carte
    respond_to do |format|
      format.html { redirect_to card_path(card) }
      format.json { render json: { status: 'added' }, status: :ok }
    end
  end

  def remove_from_collection
    card = Card.find(params[:id])

    # Si le Pokémon est dans la collection de l'utilisateur, on le retire
    if current_user.cards.exists?(card.id)
      current_user.cards.destroy(card)
      flash[:notice] = 'Ce Reloumon a été retiré de votre collection.'  # Message de succès
    else
      flash[:alert] = 'Ce Reloumon n\'est pas dans votre collection.'  # Message d'alerte si le Pokémon n'est pas dans la collection
    end

    # Redirection vers la page de la carte
    respond_to do |format|
      format.html { redirect_to card_path(card) }
      format.json { render json: { status: 'removed' }, status: :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def collection
    @user = User.find(params[:id])
    @cards = @user.cards
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/index.html.erb
<div class="menu-card">

  <nav id="navbar">
    <ul>
      <li><%= link_to "Cartes", root_path %></li>
      <li><%= link_to "Collection", collection_user_path(current_user) if user_signed_in? %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Connexion", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>

  <div id="logo">
    <%= image_tag 'logo.png', alt: 'Logo', id: 'logo' %>
    <h2>Attrapez les tous!</h2>
  </div>


  <div class="image-card">
    <% @cards.each do |card| %>
      <div>
      <%= link_to card_path(card) do %>
        <%= image_tag(card.image_path, alt: card.name) %>
      <% end %>
      </div>
    <% end %>
</div>


</div>
<div id="footer" style="margin-top:40px">
  Réalisé par @nuagecreate
</div>

app/views/cards/show.html.erb
<div class="show-card" data-controller="modals">
  <nav id="navbar">
    <ul>
      <li><%= link_to "Cartes", root_path %></li>
      <li><%= link_to "Collection", collection_user_path(current_user) if user_signed_in? %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Connexion", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>

  <div id="logo">
    <%= image_tag 'logo.png', alt: 'Logo', id: 'logo' %>
    <h2>Attrapez les tous!</h2>
  </div>

  <div class="div-show-card">
    <div class="div-show-card-content">
      <h1><%= @card.name %></h1>
      <p><strong>Catégorie : </strong><%= @card.category %></p>
      <p><strong>Description : </strong><%= @card.description %></p>
      <p><strong>PV : </strong><%= @card.pv %></p>

      <div style="display: flex; flex-direction: row; justify-content: left; gap: 30px; margin-top: 10%">
          <% if @in_collection %>
            <%= button_to "Relâcher", remove_from_collection_card_path(@card), method: :delete, class: "action-button" %>
          <% else %>
            <%= button_to "Attraper", add_to_collection_card_path(@card), method: :post, class: "action-button" %>
          <% end %>
        <%= link_to "Retour", root_path %>
      </div>
    </div>

    <div class="div-show-card-photo">
       <%= image_tag(@card.image_path, alt: @card.name) %>
    </div>
  </div>



</div>

<div id="footer">
  Réalisé par @nuagecreate
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reloumons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">


  </head>

 <body>
   <% if flash[:notice] %>
    <div class="alert alerte-success" style="font-family: 'Lilita One'; font-size: 27px; color: #FFCC03">
      <%= flash[:notice] %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/collection.html.erb
<div class="collection-card">


  <nav id="navbar">
    <ul>
      <li><%= link_to "Cartes", root_path %></li>
      <li><%= link_to "Collection", collection_user_path(current_user) if user_signed_in? %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Connexion", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>

    <div id="logo">
    <%= image_tag 'logo.png', alt: 'Logo', id: 'logo' %>
    <h2>Attrapez les tous</h2>
  </div>
    <div class="titre-collection">
      <h1>Ma collection</h1>
    </div>
    <div class="collection-image-card">
      <% @cards.each do |card| %>
        <div class="card">
          <%= link_to card_path(card) do %>
          <%= image_tag card.photo if card.photo.attached? %>
          <% end %>
        </div>
      <% end %>
    </div>
</div>